name: CI

on:
  push:
    branches:
      - main
      - renovate/**

  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: macos-15
    steps:
    - name: Setup build environment
      uses: msfjarvis/compose-lobsters/.github/reusable-workflows/setup-gradle@943398bb67f2501f07d5e2ad8e062cb05bb3cd2a # main
      with:
        fetch-depth: 0
        cache-read-only: ${{ github.ref != 'refs/heads/main' }}
        dependency-graph: generate-and-submit

    - name: Run unit tests
      run: ./gradlew --no-configuration-cache --stacktrace :build-logic:check check -PslimTests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: (Fail-only) Upload test report
      if: failure()
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
          name: Test report
          path: '**/build/reports/tests/**'

  dependency-review:
    runs-on: macos-15
    if: "github.event_name == 'push' && github.event.ref != 'refs/heads/main'"
    needs:
      - check
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Dependency Review
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0
        with:
          base-ref: refs/heads/main
          head-ref: ${{ github.ref }}
